version: 3
services:
  {{_name_}}:
    image: {{_cursor_}}
    container_name: {{_name_}}
    network_mode: "host"
    environment:
      - SAMPLE_USER=user
    ports:
      # - "host:guest"
      - "80:80"
      - "5900:5900"
    volumes:
      - ./share:/mnt/share
      - ${HOME}/dir:/root/dir
    command: "/run.sh  \
              --args 1 2 3"
	build_sample:
    container_name: build_sample
    build:
      context: ./my_Dockerfile_dir/
      dockerfile: Dockerfile
    # tty: true
    # privileged: true
    # mem_limit: "1024m"


# vim: set tabstop=2 shiftwidth=2 expandtab:

