version: "3"
services:
  app:
    image: ubuntu:18.04{{_cursor_}}
    # network_mode: "host"
    environment:
      - SAMPLE_USER=user
    ports:
      # - "host:guest"
      - "80:80"
      - "5900:5900"
    volumes:
      - ./share:/mnt/share
      - ${HOME}/dir:/root/dir
    command: "tail  \
          -f \
          /dev/null"
  {{_expr_:expand("%:p:h:t")}}:
    # container_name: build_sample
    build:
      context: ./my_Dockerfile_dir/
      dockerfile: Dockerfile
      # tty: true
      # privileged: true
      # mem_limit: "1024m"

