name: CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Create Release.txt
        run: |
          (
            printf "repository_url\t%s\n", "${{github.repositoryUrl}}"
            printf "ref\t%s\n", "${{github.ref}}"
            printf "ref\t%s\n", "${{github.sha}}"
          ) | tee "Release.txt"

      - name: Create assets
        run: |
          touch release.tar.gz
          tar \
          --exclude ".gitignore" \
          --exclude ".gitmodules" \
          --exclude ".git" \
          --exclude ".github" \
          --exclude "dev-tool" \
          --exclude 'release.tar.gz' \
          -zcvf release.tar.gz .
      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: release.tar.gz
          path: release.tar.gz

      - name: Create Release (on push tags only)
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name:  ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            **Full Changelog**: https://github.com/rmatttu/vimrc/compare/0.0.0...0.0.0
          draft: true
          prerelease: false

      - name: Upload Release Assets  (on push tags only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/gzip
