name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-.git-dir
          path: |
            ./
            !dist/.git/*

      - name: echo HASH
        run: echo ${{ github.sha }} > Release.txt

      - name: Archive
        run: |
          touch release.tar.gz
          tar --exclude='.git' --exclude='release.tar.gz' -zcvf release.tar.gz .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release.tar.gz
          draft: true
